name: Trigger auto deployment for ai-service

# When this action will be executed
on:
  # Automatically trigger it when changes are detected in the repo
  push:
    branches: [ main ]
    paths:
      - 'ai-service/**'
      - '.github/workflows/ai-service-AutoDeployTrigger-756c564b-ffba-4b56-b1a3-a7461fc60faf.yml'
  # Allow manual trigger 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write # Required for requesting the OIDC JWT Token
      contents: read  # Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NAIMATAISERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NAIMATAISERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NAIMATAISERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ./ai-service
          dockerfilePath: Dockerfile
          registryUrl: naimatregistry.azurecr.io
          registryUsername: ${{ secrets.NAIMAT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NAIMAT_REGISTRY_PASSWORD }}
          containerAppName: naimat-ai-service
          resourceGroup: naimat-dev_group
          imageToBuild: naimatregistry.azurecr.io/ai-service:${{ github.sha }}
          ingress: external
          targetPort: 80
          trafficWeight: 100
