name: Trigger auto deployment for ai-service

on:
  # Automatically trigger when changes are pushed
  push:
    branches: 
      [ main ]
    paths:
      - 'ai-service/**'
      - '.github/workflows/ai-service-AutoDeployTrigger.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write # Required for OIDC JWT Token
      contents: read # Required to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NAIMATBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NAIMATBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NAIMATBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ./ai-service
          dockerfilePath: Dockerfile
          registryUrl: naimatregistry.azurecr.io
          registryUsername: ${{ secrets.NAIMATBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NAIMATBACKEND_REGISTRY_PASSWORD }}
          containerAppName: ai-service
          resourceGroup: naimat-dev_group
          imageToBuild: naimatregistry.azurecr.io/ai-service:${{ github.sha }}
