name: Trigger auto deployment for naimat-backend

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/naimat-backend-AutoDeployTrigger-cf9c3b96-e841-4ea2-80f8-60283b85da9a.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NAIMATBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NAIMATBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NAIMATBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ./backend
          dockerfilePath: Dockerfile
          registryUrl: naimatregistry.azurecr.io
          registryUsername: ${{ secrets.NAIMAT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NAIMAT_REGISTRY_PASSWORD }}
          containerAppName: naimat-backend
          resourceGroup: naimat-dev_group
          imageToBuild: naimatregistry.azurecr.io/naimat-backend:${{ github.sha }}
